run: python3 dlstreamrun
detect:
  device: GPU
  ie-config: "CLDNN_PLUGIN_THROTTLE=1"
  precision: FP16
decode:
  device: GPU
detect-queue:
  enabled: false
decode-queue:
  enabled: false
sink:
  sync: true 
