run: "python3 dlstreamrun"
decode:
  device: GPU
  caps: video/x-raw\(memory:VASurface\)
detect:
  device: GPU.0
  nireq: 1
  batch-size: 1
  pre-process-backend: vaapi-surface-sharing
  precision: FP32-INT8
classify-0:
  device: GPU.0
  nireq: 1
  batch-size: 1
  pre-process-backend: vaapi-surface-sharing
  precision: FP32-INT8
decode-queue:
  enabled: false
detect-queue:
  enabled: false
classify-0-queue:
  enabled: false

