run: python3 dlstreamrun
decode:
  device: GPU
  caps: video/x-raw(memory:VASurface)
classify-0:
  device: GPU
  batch-size: 1
  pre-process-backend: vaapi-surface-sharing
  inference-region: full-frame
  pre-process-config: "VAAPI_FAST_SCALE_LOAD_FACTOR=1"
  precision: FP16
  model-instance-id: cls
classify-0-queue:
  enabled: false
decode-queue:
  enabled: false
