# Runner specific configuration

run: "python3 dlstreamrun"

detect:
  device: CPU

density:
  decode:
    max-threads: 1
    device: CPU
  detect:
    cpu-throughput-streams: 1
    nireq: 2
    ie-config: "CPU_THREADS_NUM=1,CPU_BIND_THREAD=NO"
  
