run: "python3 dlstreamrun"
decode:
  device: GPU
  post-proc-caps: video/x-raw(memory:VASurface)
detect:
  device: GPU
  pre-process-backend: vaapi-surface-sharing
  scale-method: fast
  batch-size: 4
  nireq: 4
  inference-interval: 3
  model-instance-id: detect
inference-0:
  device: GPU
  pre-process-backend: vaapi-surface-sharing
  scale-method: fast
  batch-size: 4
  nireq: 4
  inference-region: roi-list
  object-class: "person"
  inference-interval: 3
  model-instance-id: inference
classify-0:
  device: GPU
  pre-process-backend: vaapi-surface-sharing
  scale-method: fast
  batch-size: 4
  nireq: 4
  inference-interval: 3
  model-instance-id: classify
overlay:
  device: GPU
  caps: video/x-h265
