od-h264-ssd-mobilenet-v1-coco
od-h265-ssd-mobilenet-v1-coco
oc-h264-full_frame-resnet-50-tf
oc-h265-full_frame-resnet-50-tf
oc-h264-ssd-mobilenet-v1-coco-resnet-50-tf
oc-h265-ssd-mobilenet-v1-coco-resnet-50-tf
ot-yolov5s-personreid
odm-h264-yolov5m-640-efficientnet-b0-dbnet
ot-oc-yolov5m
