run: "python3 dlstreamrun"
decode:
  device: CPU
  post-proc-caps: video/x-raw,format=BGRx,width=300,height=300
detect:
  device: CPU
  pre-process-backend: ie
  precision: FP16-INT8
classify-0:
  device: CPU
  pre-process-backend: ie
  precision: FP32-INT8
