run: python3 dlstreamrun
decode:
  device: GPU
  caps: video/x-raw(memory:VASurface)
detect:
  device: CPU
  cpu-throughput-streams: 1
  nireq: 2
  batch-size: 64
  pre-process-backend: opencv
  precision: FP32-INT8
  ie-config: "CPU_THREADS_NUM=1,CPU_BIND_THREAD=NO"
sink:
  sync: true