run: "python3 dlstreamrun"
decode:
  device: GPU
  caps: video/x-raw(memory:VASurface)
detect:
  device: GPU
  nireq: 4
  batch-size: 4
  pre-process-backend: vaapi-surface-sharing
  pre-process-config: "VAAPI_FAST_SCALE_LOAD_FACTOR=1"
  precision: FP16
  model-instance-id: oc-h264-yolov5m-224-resnet-50-tf-det
classify-0:
  device: GPU
  nireq: 4
  batch-size: 4
  pre-process-backend: vaapi-surface-sharing
  pre-process-config: "VAAPI_FAST_SCALE_LOAD_FACTOR=1"
  precision: FP16
  model-instance-id: oc-h264-yolov5m-224-resnet-50-tf-cls
decode-queue:
  enabled: false
detect-queue:
  enabled: false
classify-0-queue:
  enabled: false
