run: "python3 dlstreamrun"
streams-per-process: 2
decode:
  device: GPU
  post-proc-caps: video/x-raw(memory:VASurface)
detect:
  device: GPU
  precision: FP16-INT8
  nireq: 2
  gpu-throughput-streams: 1
  pre-process-backend: vaapi
  batch-size: 16
  model-instance-id: det
classify-0:
  device: GPU
  precision: FP32-INT8
  nireq: 6
  gpu-throughput-streams: 5
  pre-process-backend: vaapi
  batch-size: 16
  model-instance-id: cls
