run: "python3 dlstreamrun"
streams-per-process: 1
decode:
  device: GPU
  post-proc-caps: video/x-raw(memory:VASurface)
detect:
  device: MULTI:CPU,GPU
  precision: FP16-INT8
  model-instance-id: det
classify-0:
  device: MULTI:CPU,GPU
  precision: FP16-INT8
  model-instance-id: cls
  pre-process-backend: opencv
sink:
  sync: true
