run: python3 dlstreamrun
decode:
  device: GPU
  post-proc-caps: video/x-raw,format=BGRx
detect:
  device: HDDL
  nireq: 100
classify-0:
  device: GPU
  nireq: 100
classify-1:
  device: GPU
  nireq: 100
