run: python3 dlstreamrun
decode:
  device: GPU
  post-proc-caps: video/x-raw\(memory:VASurface\)
detect:
  device: HDDL
  nireq: 100
classify-0:
  device: GPU
  nireq: 100
classify-1:
  device: GPU
  nireq: 100
detect-queue:
  enabled: false
decode-queue:
  enabled: true
