# Runner specific configuration
run: "python3 dlstreamrun"
decode:
  device: CPU
detect:
  device: CPU
classify-0:
  device: CPU
classify-1:
  device: CPU

density:
  decode:
    device: CPU
    max-threads: 1
  detect:
    cpu-throughput-streams: 1
    ie-config: "CPU_THREADS_NUM=4,CPU_BIND_THREAD=NO"
    nireq: 4
  classify-0:
    cpu-throughput-streams: 1
    ie-config: "CPU_THREADS_NUM=4,CPU_BIND_THREAD=NO"
    nireq: 4
  classify-1:
    cpu-throughput-streams: 1
    ie-config: "CPU_THREADS_NUM=4,CPU_BIND_THREAD=NO"
    nireq: 4
