# Runner specific configuration

run: "python3 dlstreamrun"

decode:
  max-threads: 1
  device: CPU
detect:
  cpu-throughput-streams: 2
  nireq: 3
  ie-config: "CPU_THREADS_NUM=2,CPU_BIND_THREAD=NO"
  pre-process-backend: ie
  precision: FP32-INT8
  
