run: "python3 dlstreamrun"
decode:
  max-threads: 1
  device: CPU
  post-proc-caps: video/x-raw,format=BGRx,width=416,height=416
detect:
  device: CPU
  cpu-throughput-streams: 1
  nireq: 2
  pre-process-backend: ie
  precision: FP32-INT8
  ie-config: "CPU_THREADS_NUM=1,CPU_BIND_THREAD=NO"
sink:
  sync: true