run: python3 dlstreamrun
detect:
  device: HDDL
  nireq: 100
decode:
  post-proc-caps: video/x-raw\(memory:VASurface\),height=300,width=300
  device: GPU
detect-queue:
  enabled: false
decode-queue:
  enabled: true
